[package]
name = "universal-android-debloater"
version = "1.0.0"
edition = "2021"

[dependencies]
eframe = "0.26"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
include_dir = "0.7"